title: Ikutaro Hamada
description: Computational Materials Physics | Electronic structure theory, Surface and Interface Science

remote_theme: just-the-docs/just-the-docs
color_scheme: light

plugins:
  - jekyll-remote-theme

url: https://ikuhamada.github.io

markdown: kramdown

aux_links:
  GitHub:
    - https://github.com/ikuhamada
  Google Scholar:
    - https://scholar.google.com/
  ORCID:
    - https://orcid.org/0000-0001-5112-2452

footer_content: "Copyright Ikutaro Hamada"

nav_enabled: true
heading_anchors: true
search_enabled: true
